on:
    push:
      branches: [ main ]
jobs: 
        PowerShellDemo:
          name: "PowerShell Demo"
          runs-on: ubuntu-latest
      
          steps:
            - name: Login via Az module
              uses: azure/login@v1
              with:
               creds: ${{secrets.AZURE_CREDENTIALS}}
               enable-AzPSSession: true

            - name: Create an RG and SA
              uses: azure/powershell@v1
              with:
                inlineScript: |
                  Install-Module -Name Az -Repository PSGallery -Force 
                   # RG creation

                    New-AzResourceGroup -Name 'skywave-rg' -Location 'South India'

                  # Storage Account creation

                    New-AzStorageAccount -ResourceGroupName 'skywave-rg' -Name 'skywavestorageaccount' -Location 'South India' -SkuName Standard_LRS -Kind StorageV2 -AssignIdentity 
  
                    ## Function to create the storage container  

                   $storageAcc=Get-AzStorageAccount -ResourceGroupName 'skywave-rg' -Name 'skywavestorageaccount'      
                  ## Get the storage account context  
                   $ctx=$storageAcc.Context      
    
                   New-AzStorageContainer -Name 'skywavecontainer' -Context $ctx -Permission Container 
                azPSVersion: "latest"
