on:
    push:
      branches: [ main ]
jobs: 
        PowerShellDemo:
          name: "PowerShell Demo"
          runs-on: ubuntu-latest
      
          steps:
            - name: Login via Az module
              uses: azure/login@v1
              with:
               creds: ${{secrets.AZURE_CREDENTIALS}}
               enable-AzPSSession: true

            - name: Create an RG and SA
              uses: azure/powershell@v1
              with:
                inlineScript: |
                  Install-Module -Name Az -Repository PSGallery -Force 
                  $rg = New-AzResourceGroup -Name 'sample-rg' -Location 'eastus'
                  New-AzStorageAccount -ResourceGroupName $rg.Name -Location $rg.Location -Name 'superawesomedemosa01' -SkuName Standard_LRS
                azPSVersion: "latest"
