on:
    push:
      branches: [ main ]
jobs: 
        PowerShellDemo:
          name: "PowerShell Demo"
          runs-on: ubuntu-latest
      
          steps:
            - name: Login via Az module
              uses: azure/login@v1
              with:
               creds: ${{secrets.AZURE_CREDENTIALS}}
               enable-AzPSSession: true

            - name: Create an RG and SA
              uses: azure/powershell@v1
              with:
                inlineScript: |
                  Install-Module -Name Az -Repository PSGallery -Force 
                  $rg = New-AzResourceGroup -Name 'skywave-rg' -Location 'South India'
                  New-AzStorageAccount -ResourceGroupName 'skywave-rg' -Location 'South India' -Name 'skywavestorageaccount' -SkuName Standard_LRS
                  $storageAcc=Get-AzStorageAccount -ResourceGroupName 'skywave-rg' -Name 'skywavestorageaccount'
                  $ctx=$storageAcc.Context
                  New-AzStorageContainer -Name 'skywavecontainer' -Context $ctx -Permission Container  
                azPSVersion: "latest"
